-- AlterTable
ALTER TABLE "Profiles" ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "resetToken" DROP NOT NULL,
ALTER COLUMN "codeOTP" DROP NOT NULL,
ALTER COLUMN "OTPlimit" DROP NOT NULL,
ALTER COLUMN "OTPlimit" DROP DEFAULT;
